package crypto

import (
	stdcrypto "crypto"
	"crypto/ecdsa"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"time"
)

// Verdict represents a signed evaluation verdict.
// The Assessor signs this after completing a policy evaluation run,
// producing a cryptographic proof that the verdict was generated by an
// authorized Assessor instance and has not been tampered with.
type Verdict struct {
	RunID          string    `json:"run_id"`
	LedgerHash     string    `json:"ledger_hash"`
	ControlsPassed int       `json:"controls_passed"`
	ControlsFailed int       `json:"controls_failed"`
	ControlsTotal  int       `json:"controls_total"`
	Timestamp      time.Time `json:"timestamp"`
	Signature      string    `json:"signature"`
}

// SignVerdict signs a Verdict using the provided crypto.Signer (Key C / Assessor signing key).
// The Signature field is excluded from the signing input by zeroing it first.
func SignVerdict(verdict *Verdict, signer stdcrypto.Signer) error {
	if signer == nil {
		return fmt.Errorf("signer is nil")
	}

	if verdict.RunID == "" {
		return fmt.Errorf("run ID is empty")
	}

	if verdict.LedgerHash == "" {
		return fmt.Errorf("ledger hash is empty")
	}

	// Zero the signature before computing so it is excluded from the hash.
	verdict.Signature = ""

	canonical, err := json.Marshal(verdict)
	if err != nil {
		return fmt.Errorf("failed to marshal verdict: %w", err)
	}

	hash := sha256.Sum256(canonical)
	sigBytes, err := signer.Sign(rand.Reader, hash[:], nil)
	if err != nil {
		return fmt.Errorf("failed to sign verdict: %w", err)
	}

	verdict.Signature = hex.EncodeToString(sigBytes)

	return nil
}

// VerifyVerdict verifies the ECDSA signature of a Verdict.
func VerifyVerdict(verdict *Verdict, publicKey *ecdsa.PublicKey) (bool, error) {
	if publicKey == nil {
		return false, fmt.Errorf("public key is nil")
	}

	originalSig := verdict.Signature
	if originalSig == "" {
		return false, fmt.Errorf("signature is empty")
	}

	sigBytes, err := hex.DecodeString(originalSig)
	if err != nil {
		return false, fmt.Errorf("failed to decode signature: %w", err)
	}

	verdict.Signature = ""

	canonical, err := json.Marshal(verdict)
	if err != nil {
		verdict.Signature = originalSig
		return false, fmt.Errorf("failed to marshal verdict: %w", err)
	}

	hash := sha256.Sum256(canonical)
	verdict.Signature = originalSig

	return ecdsa.VerifyASN1(publicKey, hash[:], sigBytes), nil
}
