package render

import (
	"fmt"
	"io"
	"strings"
	"time"
)

// RenderPDF writes a compliance posture report as a valid PDF 1.4 document.
// This is a pure Go implementation with no external dependencies. It produces
// a text-based PDF suitable for executive review.
func RenderPDF(w io.Writer, data *HTMLData) error {
	if data.GeneratedAt == "" {
		data.GeneratedAt = time.Now().UTC().Format("2006-01-02 15:04 UTC")
	}

	p := &pdfWriter{w: w}
	p.begin()

	// Catalog + Pages.
	catalogRef := p.addObject("<<\n/Type /Catalog\n/Pages 2 0 R\n>>")
	_ = catalogRef

	// Build page content.
	var content strings.Builder

	// Title.
	content.WriteString("BT\n/F1 18 Tf\n50 780 Td\n")
	content.WriteString(fmt.Sprintf("(%s) Tj\n", pdfEscape("Jula Controls - Compliance Posture Report")))
	content.WriteString("ET\n")

	// Timestamp.
	content.WriteString("BT\n/F1 9 Tf\n0.5 0.5 0.5 rg\n50 760 Td\n")
	content.WriteString(fmt.Sprintf("(%s) Tj\n", pdfEscape("Generated: "+data.GeneratedAt)))
	content.WriteString("0 0 0 rg\nET\n")

	y := 735.0

	// Summary section.
	if data.Summary != nil {
		y = pdfSection(&content, y, "Executive Summary")

		rateText := fmt.Sprintf("%.0f%% compliant (%d/%d controls passed)",
			data.Summary.PassRate, data.Summary.Passed, data.Summary.TotalControls)
		y = pdfLine(&content, y, rateText, 12, false)

		if data.Summary.RunID != "" {
			y = pdfLine(&content, y, fmt.Sprintf("Run: %s  |  %s", data.Summary.RunID, data.Summary.Timestamp), 9, true)
		}
		if data.Summary.VerdictVerified {
			y = pdfLine(&content, y, "Verdict: VERIFIED (Key C)  |  Ledger Hash: "+truncate(data.Summary.LedgerHash, 32), 9, true)
		} else if data.Summary.VerdictSigned {
			y = pdfLine(&content, y, "Verdict: SIGNED (unverified)  |  Ledger Hash: "+truncate(data.Summary.LedgerHash, 32), 9, true)
		}

		y -= 5

		// Family table header.
		y = pdfTableHeader(&content, y, []string{"Control Family", "Passed", "Failed", "Pass Rate"}, []float64{50, 250, 320, 390})

		for _, f := range data.Summary.Families {
			y = pdfTableRow(&content, y, []string{
				f.Name,
				fmt.Sprintf("%d", f.Passed),
				fmt.Sprintf("%d", f.Failed),
				fmt.Sprintf("%.0f%%", f.PassRate),
			}, []float64{50, 250, 320, 390})

			if y < 80 {
				break // Avoid writing off-page.
			}
		}

		y -= 10

		// Failed controls.
		if len(data.Summary.FailedControls) > 0 {
			y = pdfSection(&content, y, "Failed Controls")
			for _, fc := range data.Summary.FailedControls {
				detail := truncate(fc.Details, 60)
				y = pdfLine(&content, y, fmt.Sprintf("%-10s %s", fc.ControlID, detail), 9, false)
				if y < 80 {
					break
				}
			}
			y -= 10
		}
	}

	// Coverage section.
	if data.Coverage != nil && y > 120 {
		y = pdfSection(&content, y, "Automation Coverage")
		y = pdfLine(&content, y, fmt.Sprintf("Fully Automated: %d (%.0f%%)", data.Coverage.FullyAutomated, data.Coverage.PctFull), 10, false)
		y = pdfLine(&content, y, fmt.Sprintf("Partially Auto:  %d (%.0f%%)", data.Coverage.PartiallyAuto, data.Coverage.PctPartial), 10, false)
		y = pdfLine(&content, y, fmt.Sprintf("Manual Audit:    %d (%.0f%%)", data.Coverage.ManualAudit, data.Coverage.PctManual), 10, false)
		y -= 10
	}

	// Maturity section.
	if data.Maturity != nil && y > 120 {
		y = pdfSection(&content, y, "NIST CSF Maturity")
		y = pdfLine(&content, y, fmt.Sprintf("Overall Maturity: %.0f%%", data.Maturity.OverallScore*100), 11, false)
		y -= 3
		for _, f := range data.Maturity.Functions {
			label := fmt.Sprintf("%s - %s", f.ID, f.Name)
			y = pdfLine(&content, y, fmt.Sprintf("%-20s  %.0f%%  (%d controls)", label, f.Score*100, f.Total), 9, false)
			if y < 80 {
				break
			}
		}
		y -= 10
	}

	// Risk section.
	if data.Risk != nil && y > 120 {
		y = pdfSection(&content, y, "FAIR Risk Analysis")
		y = pdfTableHeader(&content, y, []string{"Family", "Failed", "ALE", "95th Pct", "Mit. Cost", "ROI"}, []float64{50, 200, 260, 330, 400, 470})

		for _, r := range data.Risk.Results {
			y = pdfTableRow(&content, y, []string{
				r.Family,
				fmt.Sprintf("%d", r.ControlsFailed),
				fmtMoneyPDF(r.ALE),
				fmtMoneyPDF(r.Loss95th),
				fmtMoneyPDF(r.MitigationCost),
				fmt.Sprintf("%.0f%%", r.ROI),
			}, []float64{50, 200, 260, 330, 400, 470})
			if y < 80 {
				break
			}
		}
		y -= 5
		y = pdfLine(&content, y, fmt.Sprintf("Total ALE: %s  |  95th Pct: %s  |  Mitigation: %s",
			fmtMoneyPDF(data.Risk.TotalALE), fmtMoneyPDF(data.Risk.TotalLoss95), fmtMoneyPDF(data.Risk.TotalMitCost)), 9, true)
	}

	// Footer.
	content.WriteString("BT\n/F1 7 Tf\n0.5 0.5 0.5 rg\n200 30 Td\n")
	content.WriteString(fmt.Sprintf("(%s) Tj\n", pdfEscape("Generated by jula-posture | Jula Controls")))
	content.WriteString("0 0 0 rg\nET\n")

	contentStr := content.String()

	// Stream object for page content.
	streamObj := fmt.Sprintf("<<\n/Length %d\n>>\nstream\n%sendstream", len(contentStr), contentStr)
	streamRef := p.addObject(streamObj)

	// Font object (Helvetica, built into all PDF readers).
	fontRef := p.addObject("<<\n/Type /Font\n/Subtype /Type1\n/BaseFont /Helvetica\n>>")

	// Page object.
	pageObj := fmt.Sprintf("<<\n/Type /Page\n/Parent 2 0 R\n/MediaBox [0 0 612 792]\n/Contents %d 0 R\n/Resources <<\n/Font <<\n/F1 %d 0 R\n>>\n>>\n>>", streamRef, fontRef)
	pageRef := p.addObject(pageObj)

	// Pages object (must be object 2).
	p.objects[1] = fmt.Sprintf("<<\n/Type /Pages\n/Kids [%d 0 R]\n/Count 1\n>>", pageRef)

	return p.finish()
}

// --- PDF Writer internals ---

type pdfWriter struct {
	w       io.Writer
	objects []string
	offsets []int
	pos     int
}

func (p *pdfWriter) begin() {
	// Reserve object 1 (catalog) and object 2 (pages).
	p.objects = make([]string, 2)
}

func (p *pdfWriter) addObject(content string) int {
	p.objects = append(p.objects, content)
	return len(p.objects) // 1-based index.
}

func (p *pdfWriter) write(s string) {
	n, _ := fmt.Fprint(p.w, s)
	p.pos += n
}

func (p *pdfWriter) finish() error {
	// Write header.
	p.write("%PDF-1.4\n")

	// Write objects.
	p.offsets = make([]int, len(p.objects))
	for i, obj := range p.objects {
		p.offsets[i] = p.pos
		p.write(fmt.Sprintf("%d 0 obj\n%s\nendobj\n", i+1, obj))
	}

	// Write xref table.
	xrefPos := p.pos
	p.write(fmt.Sprintf("xref\n0 %d\n", len(p.objects)+1))
	p.write("0000000000 65535 f \n")
	for _, off := range p.offsets {
		p.write(fmt.Sprintf("%010d 00000 n \n", off))
	}

	// Write trailer.
	p.write(fmt.Sprintf("trailer\n<<\n/Size %d\n/Root 1 0 R\n>>\nstartxref\n%d\n%%%%EOF\n",
		len(p.objects)+1, xrefPos))

	return nil
}

// --- PDF content helpers ---

func pdfEscape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "(", "\\(")
	s = strings.ReplaceAll(s, ")", "\\)")
	return s
}

func pdfSection(content *strings.Builder, y float64, title string) float64 {
	y -= 5
	// Underline.
	content.WriteString(fmt.Sprintf("0.6 0.6 0.6 RG\n0.5 w\n50 %.1f m 550 %.1f l S\n", y, y))
	y -= 15
	content.WriteString(fmt.Sprintf("BT\n/F1 12 Tf\n50 %.1f Td\n(%s) Tj\nET\n", y, pdfEscape(title)))
	y -= 15
	return y
}

func pdfLine(content *strings.Builder, y float64, text string, fontSize float64, dimmed bool) float64 {
	if dimmed {
		content.WriteString("BT\n")
		content.WriteString(fmt.Sprintf("/F1 %.0f Tf\n0.4 0.4 0.4 rg\n", fontSize))
	} else {
		content.WriteString("BT\n")
		content.WriteString(fmt.Sprintf("/F1 %.0f Tf\n0 0 0 rg\n", fontSize))
	}
	content.WriteString(fmt.Sprintf("50 %.1f Td\n(%s) Tj\nET\n", y, pdfEscape(text)))
	return y - (fontSize + 3)
}

func pdfTableHeader(content *strings.Builder, y float64, headers []string, xPositions []float64) float64 {
	content.WriteString(fmt.Sprintf("BT\n/F1 8 Tf\n0.3 0.3 0.3 rg\n"))
	for i, h := range headers {
		content.WriteString(fmt.Sprintf("%.1f %.1f Td\n(%s) Tj\n", xPositions[i], y, pdfEscape(h)))
		if i < len(headers)-1 {
			// Reset position for next column.
			content.WriteString(fmt.Sprintf("%.1f %.1f Td\n", -xPositions[i], -y))
		}
	}
	content.WriteString("0 0 0 rg\nET\n")

	// Header underline.
	content.WriteString(fmt.Sprintf("0.7 0.7 0.7 RG\n0.3 w\n50 %.1f m 540 %.1f l S\n", y-2, y-2))

	return y - 14
}

func pdfTableRow(content *strings.Builder, y float64, values []string, xPositions []float64) float64 {
	content.WriteString(fmt.Sprintf("BT\n/F1 8 Tf\n0 0 0 rg\n"))
	for i, v := range values {
		content.WriteString(fmt.Sprintf("%.1f %.1f Td\n(%s) Tj\n", xPositions[i], y, pdfEscape(v)))
		if i < len(values)-1 {
			content.WriteString(fmt.Sprintf("%.1f %.1f Td\n", -xPositions[i], -y))
		}
	}
	content.WriteString("ET\n")
	return y - 12
}

func fmtMoneyPDF(v float64) string {
	if v >= 1000000 {
		return fmt.Sprintf("$%.1fM", v/1000000)
	}
	if v >= 1000 {
		return fmt.Sprintf("$%.0fK", v/1000)
	}
	return fmt.Sprintf("$%.0f", v)
}

func truncate(s string, maxLen int) string {
	if len(s) > maxLen {
		return s[:maxLen-3] + "..."
	}
	return s
}
