# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "security"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
