vendor_name: "aikido"
base_url: "https://app.aikido.dev/api/public/v1"
auth_flow:
  type: "oauth2"
  token_url: "https://app.aikido.dev/api/oauth/token"
  client_id_env: "AIK_CLIENT_ID"
  client_secret_env: "AIK_SECRET_KEY"
endpoints:
  "/issues/export?format=json&filter_status=open&jula_erl=E-MNT-03":
    erl_id: "E-MNT-03"
    description: "Aikido Patch Management Audits (Open Vulnerabilities)"
  "/containers/${AIK_CONTAINER_ID}/licenses/export?format=sbom":
    erl_id: "E-TDA-03"
    description: "Aikido Container SBOM"
  "/repositories/code/${AIK_CODE_REPO_ID}/licenses/export?format=sbom&jula_erl=E-TDA-11":
    erl_id: "E-TDA-11"
    description: "Aikido Code Repository SBOM"
  "/repositories/code/${AIK_CODE_REPO_ID}/licenses/export?format=sbom&jula_erl=E-TDA-12":
    erl_id: "E-TDA-12"
    description: "Aikido Primary Software Bill of Materials (SBOM)"
  "/virtual-machines/${AIK_VM_ID}/export/sbom":
    erl_id: "E-TDA-15"
    description: "Aikido Virtual Machine SBOM"
  "/containers":
    erl_id: "E-VPM-01"
    description: "Aikido Container Inventory"
  "/report/ciScans?jula_erl=E-VPM-02":
    erl_id: "E-VPM-02"
    description: "Aikido Vulnerability Scan Report"
  "/repositories/code":
    erl_id: "E-VPM-05"
    description: "Aikido Code Repository Inventory"
  "/report/ciScans?jula_erl=E-VPM-08":
    erl_id: "E-VPM-08"
    description: "Aikido Flaw Remediation Test Results (CI Scans)"
  "/report/ciScans?jula_erl=E-VPM-09":
    erl_id: "E-VPM-09"
    description: "Aikido Flaw Remediation Actions (CI Scans)"
  "/virtual-machines":
    erl_id: "E-VPM-10"
    description: "Aikido Virtual Machine Inventory"
  "/issues/export?format=json&filter_status=open&jula_erl=E-VPM-11":
    erl_id: "E-VPM-11"
    description: "Aikido Open Vulnerability Scan"
